# 2020-08-13/widget-audit.yml
- name: performing an audit
  hosts: localhost
  connection: local
  
  
  # a collection with a callback plugin could be developed
  # of course the collection could do other things as well
  # but perhaps its last step would be pushing the log anyplace you wished
  # or handle the log any way you wanted
  # see the callback plugin called "default" to see how it is currently being handled
  
  tasks:
  - name: Demo task - Our Engineer would create this
    apt:
      state: present
      name: [figlet, apache2]
    check_mode: yes      # performing a check, we just want what is returned